apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgBoVYOaSUOAGdHG5RYzI8jPWZuYYjCzEn7l9chtShzTdPLfEgMZAgyKDl1+wg6GvSks6Yh9fUF0/AfMaHat82rHpwKOxi/KfDUBlj5o7dlYwxDHg5DlvQqt6ovGvIzEZDJ8bJ2uaml+RHraiODgn7NuZMZU84s17VvKCpa59MSZbv6dXYmR8LvUs0BiMUNA+TfY/rn6oZgpV+7NbzyTpj8qrDOcEzYqImm4ln67Ez5pO3vn4GK5qLpWrCpuiRO1gDbooRc20oZL8Mjlh7ev8k7XxBgchxN8610aDI5Yt39dSkT6cbXearvE4+ximDPKW2C46JIi/UoxNU8ttCms5BhO7/vf0o/Z2e3PgjXIdQoMBcGrMTbyB6YUdU9pyIa9bGr0ivxcYg/DCuEijjzE2bUsghPgSBw4QnuS/OsjMhBMMc0XpAsp98cFBa/e4WMjXlLq6wrM1Q9GQ3MC5vIvRJwVwMAFbA8SsALnL44C44shQUVCiiDHUV9CE0GPPg/Jh71TsU8seUQ4jI2k42bHOuES1nGOXY+CREBMilTo+s4HP56fpZ919CT7ADsWE34JKvv7aSgFF1FLwBExCK6cbDv2JMKVoWNRQYdoBxZ5i5m52UeEI2D2Q9ccYrkaaPzMBRyg0AJm78S50d3NewYZomX2+p/6WLv92lMORTMixmXR2MdUiF+dO9wMgEkqFJ6droM=
    user: AgA8XJFO6VzgpdhaULYNunYJScJyk6lNtyC2JlVAOSwng90qkecsW6/bT70AjgfHAkJrI5JMq8yeaHIkadjSPPn1/CO8wU0rBeA7JyUn3uz2uceNgCnIh0PRuo0aqdTV/vZ9UpBdv6DL0t24JLUOTBRLY51hPpC2FzAxy9NS+OMyCVasAFvKhs80QqR2mOoVStr1gdqg+ctTBrEiycSnYllQM94/RN62pXF80HX0HOhf3V2KekFtcbruQb8Pp1j9IS/w+ssdSzNQyzIjWBX+JyKyGo2HUYSGd5iHS2nb0qS6iYUNO6nsQFtaVBBuzpieo2IxjhsNUTD841O0/Pw+O7bTZU5kxgBeRzCC3SfwsUz622pG3hXGGS+NJSwQ0ILCqWkdVAiVYTmBxfZ8HsHZRmFBh5cpSgQ8PosqPLwAKVjgEBTVL3H06JQCSBA3hOfapGUoTjDO1NmYPPqKIlOx5wUykjcXH5Xt9Bm3pIkoa5AKPGUNcVTyhDOQNl7+NKDYzofL0XpE66eijucYS3W+Q/tGf7pNWBfAhBkgIefsF84C6bK1J4p6et2j2bjDnmh84UQqG936/37NmUzyp2UAGmhCxXgGTER9jd/FIrhZ0HXa4Yudt60/BVbSykGPEYWUZlREB9fdo3bLjuebTv7IzjV37pu8VB8k1kmI3quBJgwAXXXSMk916Bx/Rdy1J9rT3eLavrfFHUn1Wg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default

