apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: flux-system
spec:
  selector:
    matchLabels:
      name: postgres
  replicas: 1
  template:
    metadata:
      name: postgres
      namespace: flux-system
    spec:
      chart:
        spec:
          chart: postgresql
          sourceRef:
            kind: HelmRepository
            name: bitnami
      interval: 1m0s
      releaseName: postgresql
  env:
    - name: postgresqlPassword
      valueFrom:
        secretKeyRef:
          name: basic-auth
          key: encryptedData.password
